"use client";

/**
 * Centralized Mock Data for FinFlow
 * Realistic construction project data showing contractor-owner relationship
 */

// Helper to generate consistent IDs
function generateMockId(prefix, index) {
  return `${prefix}_mock_${Date.now()}_${index}`;
}

// Helper to get date relative to today
function getRelativeDate(daysOffset) {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString();
}

/**
 * Complete Mock Project Data
 * Represents a real-estate construction project with:
 * - Owner: Mr. Rajesh Kumar (buying apartment)
 * - Contractor: Skyline Constructions (building the complex)
 * - Project: Sunrise Meadows Residential Complex, Unit A-704
 */
export const MOCK_PROJECT_DATA = {
  // Basic Project Information
  projectName: "Sunrise Meadows - Tower A, Unit 704",
  builderName: "Skyline Constructions Pvt. Ltd.",
  
  // Financial Details
  totalCost: 8500000, // ₹85 Lakhs
  downPayment: 1500000, // ₹15 Lakhs (17.6%)
  sanctionedLoanAmount: 7000000, // ₹70 Lakhs
  annualInterestRate: 8.5, // 8.5% per annum
  loanTenureYears: 20, // 20 years
  
  // Construction Milestones (typical high-rise construction phases)
  milestones: [
    {
      id: generateMockId('ms', 1),
      name: "Foundation & Basement",
      percentageOfCost: 10,
      isCompleted: true,
      description: "Excavation, foundation laying, basement construction",
      completedDate: getRelativeDate(-180) // 6 months ago
    },
    {
      id: generateMockId('ms', 2),
      name: "Ground to 3rd Floor Structure",
      percentageOfCost: 15,
      isCompleted: true,
      description: "RCC columns, beams, slabs for ground to 3rd floor",
      completedDate: getRelativeDate(-120) // 4 months ago
    },
    {
      id: generateMockId('ms', 3),
      name: "4th to 7th Floor Structure",
      percentageOfCost: 18,
      isCompleted: true,
      description: "RCC work for 4th to 7th floor including Unit A-704",
      completedDate: getRelativeDate(-60) // 2 months ago
    },
    {
      id: generateMockId('ms', 4),
      name: "Brickwork & Plastering",
      percentageOfCost: 20,
      isCompleted: false,
      description: "Internal and external walls, plastering work",
      expectedDate: getRelativeDate(30) // 1 month from now
    },
    {
      id: generateMockId('ms', 5),
      name: "Electrical & Plumbing",
      percentageOfCost: 12,
      isCompleted: false,
      description: "Electrical wiring, plumbing, sanitary fittings",
      expectedDate: getRelativeDate(60) // 2 months from now
    },
    {
      id: generateMockId('ms', 6),
      name: "Flooring & Tiling",
      percentageOfCost: 10,
      isCompleted: false,
      description: "Vitrified tiles, bathroom tiles, kitchen platform",
      expectedDate: getRelativeDate(90) // 3 months from now
    },
    {
      id: generateMockId('ms', 7),
      name: "Painting & Finishing",
      percentageOfCost: 8,
      isCompleted: false,
      description: "Interior/exterior painting, false ceiling, fixtures",
      expectedDate: getRelativeDate(120) // 4 months from now
    },
    {
      id: generateMockId('ms', 8),
      name: "Final Handover",
      percentageOfCost: 7,
      isCompleted: false,
      description: "Final inspection, snag list clearance, possession",
      expectedDate: getRelativeDate(150) // 5 months from now
    }
  ],
  
  // Invoices generated by contractor
  invoices: [],
  
  // Transactions (payments and disbursements)
  transactions: []
};

/**
 * Generate invoices based on completed milestones
 */
function generateInvoices(project) {
  const invoices = [];
  let invoiceCounter = 10001;
  
  project.milestones.forEach((milestone, index) => {
    if (milestone.isCompleted || index === 3) { // Include current milestone
      const invoiceAmount = Math.round((project.totalCost * milestone.percentageOfCost) / 100);
      const invoice = {
        id: generateMockId('inv', index),
        milestoneId: milestone.id,
        invoiceNumber: `INV-${invoiceCounter++}`,
        amount: invoiceAmount,
        dueDate: milestone.isCompleted 
          ? milestone.completedDate 
          : getRelativeDate(7), // Due in 7 days for current milestone
        status: milestone.isCompleted ? 'Paid' : 'Due',
        issuedDate: milestone.isCompleted 
          ? new Date(new Date(milestone.completedDate).getTime() - 7*24*60*60*1000).toISOString()
          : getRelativeDate(0),
        description: `Payment for ${milestone.name}`,
        gstAmount: Math.round(invoiceAmount * 0.18), // 18% GST
        totalWithGst: Math.round(invoiceAmount * 1.18)
      };
      invoices.push(invoice);
    }
  });
  
  return invoices;
}

/**
 * Generate realistic transactions showing payment flow
 */
function generateTransactions(project, invoices) {
  const transactions = [];
  let txnCounter = 1;
  
  invoices.forEach((invoice, index) => {
    if (invoice.status === 'Paid') {
      const milestone = project.milestones.find(m => m.id === invoice.milestoneId);
      
      // Bank Disbursement (typically 80% of invoice)
      const bankAmount = Math.round(invoice.amount * 0.80);
      transactions.push({
        id: generateMockId('txn', txnCounter++),
        invoiceId: invoice.id,
        type: 'Bank Disbursement',
        amount: bankAmount,
        date: new Date(new Date(invoice.dueDate).getTime() - 3*24*60*60*1000).toISOString(),
        notes: `Bank disbursement for ${milestone.name} - 80% of invoice amount`,
        paymentMethod: 'NEFT',
        referenceNumber: `NEFT${Math.floor(Math.random() * 1000000000)}`,
        bankName: 'State Bank of India'
      });
      
      // Owner Direct Payment (remaining 20%)
      const ownerAmount = invoice.amount - bankAmount;
      transactions.push({
        id: generateMockId('txn', txnCounter++),
        invoiceId: invoice.id,
        type: 'Owner Direct Payment',
        amount: ownerAmount,
        date: new Date(new Date(invoice.dueDate).getTime() - 1*24*60*60*1000).toISOString(),
        notes: `Owner's contribution for ${milestone.name} - 20% of invoice amount`,
        paymentMethod: 'Cheque',
        referenceNumber: `CHQ${Math.floor(Math.random() * 1000000)}`,
        bankName: 'HDFC Bank'
      });
    }
  });
  
  // Add Pre-EMI payments (monthly interest payments)
  const monthsElapsed = 6; // 6 months since first disbursement
  const totalDisbursed = transactions
    .filter(t => t.type === 'Bank Disbursement')
    .reduce((sum, t) => sum + t.amount, 0);
  
  const monthlyPreEMI = Math.round((totalDisbursed * (project.annualInterestRate / 12 / 100)));
  
  for (let i = 0; i < monthsElapsed; i++) {
    transactions.push({
      id: generateMockId('txn', txnCounter++),
      invoiceId: null,
      type: 'Pre-EMI',
      amount: monthlyPreEMI,
      date: getRelativeDate(-180 + (i * 30)), // Monthly from 6 months ago
      notes: `Pre-EMI payment for month ${i + 1} - Interest on disbursed amount`,
      paymentMethod: 'Auto-Debit',
      referenceNumber: `EMI${Math.floor(Math.random() * 1000000)}`,
      bankName: 'State Bank of India'
    });
  }
  
  return transactions;
}

/**
 * Get complete mock project with all relationships
 */
export function getCompleteMockProject() {
  const project = { ...MOCK_PROJECT_DATA };
  project.invoices = generateInvoices(project);
  project.transactions = generateTransactions(project, project.invoices);
  
  return project;
}

/**
 * Additional mock data for contractor dashboard
 */
export const MOCK_CONTRACTOR_DATA = {
  contractorName: "Skyline Constructions Pvt. Ltd.",
  contractorEmail: "info@skylineconstructions.com",
  contractorPhone: "+91-9876543210",
  gstNumber: "29ABCDE1234F1Z5",
  panNumber: "ABCDE1234F",
  
  // Project statistics
  projectStats: {
    totalProjects: 12,
    activeProjects: 5,
    completedProjects: 7,
    totalRevenue: 125000000, // ₹12.5 Crores
    pendingPayments: 8500000 // ₹85 Lakhs
  },
  
  // Team members
  team: [
    { name: "Ramesh Sharma", role: "Site Engineer", phone: "+91-9876543211" },
    { name: "Suresh Kumar", role: "Project Manager", phone: "+91-9876543212" },
    { name: "Amit Patel", role: "Supervisor", phone: "+91-9876543213" }
  ],
  
  // Resources
  resources: [
    { name: "Labor", count: 45, unit: "workers", cost: 450000 },
    { name: "Cement", count: 500, unit: "bags", cost: 175000 },
    { name: "Steel", count: 15, unit: "tons", cost: 750000 },
    { name: "Bricks", count: 50000, unit: "pieces", cost: 250000 }
  ]
};

/**
 * Additional mock data for owner dashboard
 */
export const MOCK_OWNER_DATA = {
  ownerName: "Mr. Rajesh Kumar",
  ownerEmail: "rajesh.kumar@email.com",
  ownerPhone: "+91-9123456789",
  panNumber: "ABCDE5678K",
  
  // Loan details
  loanDetails: {
    bankName: "State Bank of India",
    loanAccountNumber: "12345678901234",
    loanOfficerName: "Ms. Priya Sharma",
    loanOfficerPhone: "+91-9876501234",
    loanOfficerEmail: "priya.sharma@sbi.co.in",
    branchName: "Koramangala Branch",
    branchAddress: "123, 5th Block, Koramangala, Bangalore - 560095"
  },
  
  // Property details
  propertyDetails: {
    unitNumber: "A-704",
    tower: "Tower A",
    floor: "7th Floor",
    carpetArea: "1250 sq.ft",
    builtUpArea: "1450 sq.ft",
    facing: "East",
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    parking: "2 Covered"
  },
  
  // Payment summary
  paymentSummary: {
    totalPaid: 0, // Will be calculated
    remainingAmount: 0, // Will be calculated
    nextPaymentDue: null, // Will be calculated
    totalInterestPaid: 0 // Will be calculated
  }
};

/**
 * Calculate owner's payment summary
 */
export function calculateOwnerPaymentSummary(project) {
  const totalPaid = project.transactions
    .filter(t => t.type === 'Owner Direct Payment')
    .reduce((sum, t) => sum + t.amount, 0);
  
  const totalInterestPaid = project.transactions
    .filter(t => t.type === 'Pre-EMI')
    .reduce((sum, t) => sum + t.amount, 0);
  
  const paidInvoices = project.invoices
    .filter(inv => inv.status === 'Paid')
    .reduce((sum, inv) => sum + inv.amount, 0);
  
  const remainingAmount = project.totalCost - paidInvoices;
  
  const nextDueInvoice = project.invoices.find(inv => inv.status === 'Due');
  
  return {
    totalPaid,
    remainingAmount,
    nextPaymentDue: nextDueInvoice ? {
      amount: nextDueInvoice.amount,
      dueDate: nextDueInvoice.dueDate,
      milestone: project.milestones.find(m => m.id === nextDueInvoice.milestoneId)?.name
    } : null,
    totalInterestPaid
  };
}

/**
 * Calculate contractor's project summary
 */
export function calculateContractorProjectSummary(project) {
  const totalInvoiced = project.invoices.reduce((sum, inv) => sum + inv.amount, 0);
  const totalReceived = project.transactions
    .filter(t => t.type === 'Owner Direct Payment' || t.type === 'Bank Disbursement')
    .reduce((sum, t) => sum + t.amount, 0);
  const pendingAmount = totalInvoiced - totalReceived;
  
  const completedMilestones = project.milestones.filter(m => m.isCompleted).length;
  const totalMilestones = project.milestones.length;
  const completionPercentage = Math.round((completedMilestones / totalMilestones) * 100);
  
  return {
    totalInvoiced,
    totalReceived,
    pendingAmount,
    completedMilestones,
    totalMilestones,
    completionPercentage
  };
}

/**
 * Export all mock data
 */
export default {
  getCompleteMockProject,
  MOCK_CONTRACTOR_DATA,
  MOCK_OWNER_DATA,
  calculateOwnerPaymentSummary,
  calculateContractorProjectSummary
};
